### ISSUE TITLE
Handful of issues on Remaining Games list

### ISSUE THREAD

**Issue by ianschmidt83** [vNakamura/8bitnintendo-science#15]
Noticed a few games that could be removed from Remaining Games

1. "Toki" is already ranked
2. "Indiana Jones and the Temple of Doom" was already played.  The licensed and unlicensed versions of that game are identical.
3. "Donkey Kong Classics" is a combination cart
4. "Sesame Street: A-B-C/1-2-3" is also a combo cart

**Comment by vNakamura** [comment]
Fixed. Thanks @ianschmidt83 !
