### ISSUE TITLE
Some issues with Tengen's games

### ISSUE THREAD

**Issue by ianschmidt83** [vNakamura/8bitnintendo-science#2]
Tengen's unlicensed version of Tetris isn't showing in the "Remaining Games" list

Also, this might be expected behavior, but there are some Tengen games showing up twice as both licensed and unlicensed games

**Comment by vNakamura** [comment]
Sorry I didn't see the issues before, my notifications were not set correctly.

I'll push a fix for Tetris. Thanks!

On the duplicates, I think I'll keep both versions until Jeff plays it to decide which one to keep.
