### ISSUE TITLE
Remaining unlicensed games

### ISSUE THREAD

**Issue by Pacmantis** [vNakamura/8bitnintendo-science#8]
You probably already knew this, but a lot of the unlicensed games in the remaining list didn't get a US release.

I looked through it and figured out which ones aren't actually eligible for the rankings. Is it alright if I edit the data file to hide the ineligible games? I could give you the list if you'd prefer to make the changes yourself instead.

Thanks for making the site, by the way. It's great.

**Comment by vNakamura** [comment]
Actually, I didn't realize that. At first, the lists of licensed and unlicensed games were used just to get the release date and developer. Later, when I created the page with the remaining games, it didn't occur to me that there were games there that didn't match the criteria for the ranking. Thanks for noticing and figuring out the correct set.

Of course, feel free to edit and open the Pull Request. Thank you.
